### ISSUE TITLE
NameError: name 'MYWIFI' isn't defined

### ISSUE THREAD

**Issue by jiripaskov** [MrOstling/cat-box#1]
Hello,

thank you for your work.

I tried to upload micropython using adafruit online tool https://adafruit.github.io/Adafruit_WebSerial_ESPTool/

I used Wemos S2 Mini board.

After I upload content of SRC folder from your repo into root of S2 Mini using tool called Thonny.

Now I can see boot.py. main.py, microdot.py, folder Alert, Wifi etc - all in root folder of my device.

If I restart it and connect again with Thonny I can see Shell output which shows:
MPY: soft reboot
Traceback (most recent call last):
  File "boot.py", line 1, in <module>
  File "wifi/connection.py", line 4, in <module>
  File "wifi/secrets.py", line 1, in <module>
NameError: name 'MYWIFI' isn't defined
MicroPython v1.23.0 on 2024-06-02; LOLIN_S2_MINI with ESP32-S2FN4R2

Type "help()" for more information.

>>> 

Could you please help me what could be wrong with my wifi config? It look like this:
wifi_ssid = MYWIFI
wifi_password = Superpassword
wifi_ip_config = ('10.0.0.55', '255.255.255.0', '10.0.0.138', '8.8.8.8')
base_url = None

Thank you very much.

**Comment by jiripaskov** [comment]
So - I repaired it by using 'MYWIFI' and the same for password. Now Shell shows succesfully connected. I can PING specified IP. But there is nothing in web browser on this IP (10.0.0.55 in Chrome).

Shell shows:
MPY: soft reboot
I'm here to eat shit!
Loading: {}
Loading: {}
connecting to network...
Successfully connected to MYWIFI
('10.0.0.55', '255.255.255.0', '10.0.0.138', '8.8.8.8')
MicroPython v1.23.0 on 2024-06-02; LOLIN_S2_MINI with ESP32-S2FN4R2

Type "help()" for more information.

**Comment by jiripaskov** [comment]
Oh IT WORKS NOW :)
O forgot to reboot :)

And use http instead https. 

GREAT WORK. I will test it and will give you feedback. 

Thanks.

**Comment by jiripaskov** [comment]
So after assembling litter robot and connecting all the cables it does this:
I can see web GUI.
When I turn the power on it shows that is Waiting for a shit.
When I press Cycle button. It will start cycling (Sifting shit), But after 5 seconds it will stop the globe and showing Eating shit, Leveling litter very fast (lets say 2 and 2 seconds after). And after that is state again Waiting for a shit.
Do you think something could be with sensors ? Is there some way how to reach some log while system is working?

**It just seems like all actions are runing very fast (in few seconds...)**

Thank you.

**Comment by MrOstling** [comment]
I am glad to hear this project has been useful to someone else. It sounds like one of the hall effect sensors is tripping early. While debugging, I ran a usb cable through the old button hold in the front of the unit so I could see the log output in the terminal (note that you will want to pull the jumper on the motor controller so there aren't two 5v sources). There should be print statements in the console with the hall effect sensor values. 

It could be that your globe is moving slowly. You could try increasing the `cycle_start_ignore_hall_sensor_time` setting. This will give more time for the magent in the globe to move further away from the hall effect sensor. 

It could also be a bad sensor or resistor, or maybe a wiring issue.

**Comment by MrOstling** [comment]
Didn't mean to close the issue without resolution

**Comment by jiripaskov** [comment]
Hello and thank you for fast response.
So I will connect USB to the PC - but.
WHat should I disconnect to prevent electric problem? Is your wiring scheme OK now?
As I can see I share POWER ground (which is -12V) with +5V from L298N - is this OK?
If I unplug pins GND and VBUS from S2 Mini and plug USB-C - will it work without problems? I think there could be problem with pins 35 and 33 communicating into L298N board because this board has its own 5VDC source...
Thank you.

**Comment by jiripaskov** [comment]
OH WORKS NOW! My fault was that I had not connected (I use breadboard) one of those resistors on Hall sensor.
So now the globe works perfect.
BUT - no cat detection. I try to set sensitivity to 1, 3000 or 6000 I can´t detect anything based on weight sensor. 
Will try to check the wire connection ....

But it would be great to check it also in log via shell - but as I asked before - is it safe? I think there could be problem with two powersources. Or is there some "online" way how to check what is going on in micrypthon? Thank you.

**Comment by jiripaskov** [comment]
SOLVED - also small connection problem. So now I can start testing with real cats! GREAT WORK @MrOstling  Thank you.

**Comment by MrOstling** [comment]
Glad it worked out
